### PR TITLE
Various Deploy fixes

### LINKED ISSUE #40: Use gem instead of custom delayed_jobs Capistrano tasks
We're defining delayed_job tasks for Capistrano in our own `.cap` file. See https://github.com/sul-dlss/discovery-dispatcher/blob/master/lib/capistrano/tasks/delayed_job.cap

We could use a gem for this instead -- namely `capistrano3-delayed-job`.

### PR DESCRIPTION
**Pull request by eefahy**
Fixes #40 and is connected to #36

### CODE REVIEW

File: config/environments/development.rb [hunk 1]
```diff
@@ -22,17 +22,9 @@
...
-  # Adds additional error checking when serving assets at runtime.
-  # Checks for improperly declared sprockets dependencies.
-  # Raises helpful error messages.
-  config.assets.raise_runtime_errors = true
-
   # Raises error for missing translations
   # config.action_view.raise_on_missing_translations = true
+
+  # TODO: Move this to config gem / shared_configs
   config.purl_fetcher_url = ''
```
Comment (drh-stanford) [inline config/environments/development.rb:29]: How do the deployments get this value?

Comment (eefahy) [inline config/environments/development.rb:29]: That was to get working tests, not for deployments per se

Comment (mejackreed) [inline config/environments/development.rb:29]: Once this gets merged, it allows https://github.com/sul-dlss/discovery-dispatcher/issues/44 to get going. That will allow deployments to set per server
